default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  user: ubuntu
  password: 123
development:
  <<: *default
  database: hotel_dev

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
